language: php

# run tests on both php 5.3 and 5.4
php:
    - "5.4"
    - "5.3"

# execute unit tests, integration test stubs and integration tests using legacy storage engine
env:
    - TEST_CONFIG="phpunit.xml"
    - TEST_CONFIG="phpunit-integration.xml"
    - TEST_CONFIG="phpunit-integration-legacy.xml"

# test only master (+ Pull requests)
branches:
    only:
        - master

# setup requirements for running unit tests
before_script:
    - composer install --dev

# execute phpunit as the script command
script: "phpunit -d memory_limit=-1 -c $TEST_CONFIG"

# disable mail notifications
notification:
    email: false
